[package]
name = "color-funcs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
config = { path = "../../config" }
csscolorparser = {version="0.6", features=["lab"]}
deltae = "0.3"
# we want image 0.24.6 or later. see https://github.com/wez/wezterm/issues/3250
image = {version="0.24", git="https://github.com/image-rs/image.git", rev="fe069785ae245a2c510fd724ef96da283b05a236"}
lazy_static = "1.4"
log = "0.4"
lru = "0.7"
luahelper = { path = "../../luahelper" }
plist = "1.3"
serde = {version="1.0", features=["derive"]}
serde_json = "1.0"
serde_yaml = "0.9"
wezterm-dynamic = { path = "../../wezterm-dynamic" }
wezterm-term = { path = "../../term", features=["use_serde"] }
